### ISSUE TITLE
Duplicate rows for first craft + recraft

### ISSUE THREAD

**Issue by FayazAshraf** [SLOKnightfall/CraftersRecieptBook#3]
See Lariat creation, R4
* order was sent for a fresh craft (row created)
* a re-craft attempt was made by crafter (row created)

It is technically a craft + recraft, but it is one order, and one commission. The table makes it seem like it is two commissions.

![image](https://user-images.githubusercontent.com/12602326/221386573-6b508a88-9504-48bb-869a-062d34491883.png)

**Comment by Dalarrus** [comment]
![image](https://user-images.githubusercontent.com/12202558/222877160-a626bc74-7334-4b18-bbf5-1c449b88f581.png)

Yeah, this issue is really bad if you want to recraft as the crafter, with the exception of the two Alchemist's robes, all of those extra crafts are recrafts I did as the crafter myself. It also incorrectly adds to the total, as well as loses the order of these crafts.

**Comment by FayazAshraf** [comment]
Yeah, I opened a fix pull request here:
https://github.com/SLOKnightfall/CraftersRecieptBook/pull/4

It fixes the craft + profit calculation. And adds second-level precision to the orders when sorting (vs. day precision). 

You can patch your local plugin if you want:
https://github.com/FayazAshraf/CraftersRecieptBook

**Comment by SLOKnightfall** [comment]
The pull request with the changes has been merged and a new release has been tagged for the packager.  @FayazAshraf thanks for the help, much appreciated :)
